-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 10:35:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema baitoanbalo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baitoanbalo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baitoanbalo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `baitoanbalo` ;

-- -----------------------------------------------------
-- Table `baitoanbalo`.`balo1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitoanbalo`.`balo1` (
  `ma` VARCHAR(255) NOT NULL,
  `trongLuongBalo` DOUBLE NULL DEFAULT NULL,
  `soThuTu` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baitoanbalo`.`balo2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitoanbalo`.`balo2` (
  `ma` VARCHAR(255) NOT NULL,
  `trongLuongBalo` DOUBLE NULL DEFAULT NULL,
  `soThuTu` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baitoanbalo`.`balo3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitoanbalo`.`balo3` (
  `ma` VARCHAR(255) NOT NULL,
  `trongLuongBalo` DOUBLE NULL DEFAULT NULL,
  `soThuTu` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baitoanbalo`.`sanpham1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitoanbalo`.`sanpham1` (
  `ma` VARCHAR(255) NOT NULL,
  `ten` VARCHAR(255) NULL DEFAULT NULL,
  `trongLuong` DOUBLE NULL DEFAULT NULL,
  `giaTri` DOUBLE NULL DEFAULT NULL,
  `donGia` DOUBLE NULL DEFAULT NULL,
  `phuongAn` INT NULL DEFAULT NULL,
  `maBalo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ma`),
  INDEX `maBalo` (`maBalo` ASC) VISIBLE,
  CONSTRAINT `sanpham1_ibfk_1`
    FOREIGN KEY (`maBalo`)
    REFERENCES `baitoanbalo`.`balo1` (`ma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baitoanbalo`.`sanpham2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitoanbalo`.`sanpham2` (
  `ma` VARCHAR(255) NOT NULL,
  `ten` VARCHAR(255) NULL DEFAULT NULL,
  `trongLuong` DOUBLE NULL DEFAULT NULL,
  `giaTri` DOUBLE NULL DEFAULT NULL,
  `donGia` DOUBLE NULL DEFAULT NULL,
  `soLuong` INT NULL DEFAULT NULL,
  `phuongAn` INT NULL DEFAULT NULL,
  `maBalo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ma`),
  INDEX `maBalo` (`maBalo` ASC) VISIBLE,
  CONSTRAINT `sanpham2_ibfk_1`
    FOREIGN KEY (`maBalo`)
    REFERENCES `baitoanbalo`.`balo2` (`ma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `baitoanbalo`.`sanpham3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baitoanbalo`.`sanpham3` (
  `ma` VARCHAR(255) NOT NULL,
  `ten` VARCHAR(255) NULL DEFAULT NULL,
  `trongLuong` DOUBLE NULL DEFAULT NULL,
  `giaTri` DOUBLE NULL DEFAULT NULL,
  `donGia` DOUBLE NULL DEFAULT NULL,
  `phuongAn` INT NULL DEFAULT NULL,
  `maBalo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ma`),
  INDEX `maBalo` (`maBalo` ASC) VISIBLE,
  CONSTRAINT `sanpham3_ibfk_1`
    FOREIGN KEY (`maBalo`)
    REFERENCES `baitoanbalo`.`balo3` (`ma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
