/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.Timer;

/**
 *
 * @author OS
 */
public class MainView extends javax.swing.JFrame {
    private Balo2Form balo2Form;
    private Balo1Form balo1Form;
    private Balo3Form balo3Form;
    private InstructionsForUsePanel instructionsForUsePanel;
    private Timer titleAnimationTimer;
    private String originalTitle;
    private String animatedTitle;
    private int titleIndex = 0;
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        originalTitle = "ỨNG DỤNG GIẢI BÀI TOÁN BALO BẰNG GIẢI THUẬT TỐI ƯU";
        setTitle(originalTitle);

        // Tạo chuỗi tiêu đề chạy qua lại
        animatedTitle = originalTitle + "  "; // Thêm khoảng trắng để tạo khoảng cách giữa các lần chạy qua lại

        titleAnimationTimer = new Timer(150, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Cắt chuỗi tiêu đề để tạo hiệu ứng chạy qua lại
                setTitle(animatedTitle.substring(titleIndex, titleIndex + originalTitle.length() >= animatedTitle.length() ? animatedTitle.length() : titleIndex + originalTitle.length()));
                titleIndex = (titleIndex + 1) % animatedTitle.length();
            }
        });

        titleAnimationTimer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jButton_HuongDanSD = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButton_Balo1 = new javax.swing.JButton();
        jButton_Balo2 = new javax.swing.JButton();
        jButton_Balo3 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton_Them = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu = new javax.swing.JMenu();
        jMenuItem_Balo1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Balo2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Balo3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_HDSD = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_GioiThieu = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);
        jToolBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToolBar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToolBar1MouseExited(evt);
            }
        });

        jButton_HuongDanSD.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_HuongDanSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/huongdansd_32.png"))); // NOI18N
        jButton_HuongDanSD.setText("  Hướng dẫn  ");
        jButton_HuongDanSD.setFocusable(false);
        jButton_HuongDanSD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_HuongDanSD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_HuongDanSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HuongDanSDActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_HuongDanSD);
        jToolBar1.add(jSeparator7);

        jButton_Balo1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_Balo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/balo_32.png"))); // NOI18N
        jButton_Balo1.setText("    Balo 1    ");
        jButton_Balo1.setFocusable(false);
        jButton_Balo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Balo1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Balo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_Balo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_Balo1MouseExited(evt);
            }
        });
        jButton_Balo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Balo1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_Balo1);

        jButton_Balo2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_Balo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/balo2_32.png"))); // NOI18N
        jButton_Balo2.setText("    Balo 2    ");
        jButton_Balo2.setFocusable(false);
        jButton_Balo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Balo2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Balo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_Balo2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_Balo2MouseExited(evt);
            }
        });
        jButton_Balo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Balo2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_Balo2);

        jButton_Balo3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_Balo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/balo3_32.png"))); // NOI18N
        jButton_Balo3.setText("    Balo 3    ");
        jButton_Balo3.setFocusable(false);
        jButton_Balo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Balo3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Balo3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton_Balo3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton_Balo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_Balo3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_Balo3MouseExited(evt);
            }
        });
        jButton_Balo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Balo3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_Balo3);
        jToolBar1.add(jSeparator8);

        jButton_Them.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/about_32.png"))); // NOI18N
        jButton_Them.setText("   Giới thiệu  ");
        jButton_Them.setFocusable(false);
        jButton_Them.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Them.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_Them);

        jTabbedPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jScrollPane1.setViewportView(jTabbedPane);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/closeTab_24.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(null);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/logo.png"))); // NOI18N
        jMenu7.setText("    ");
        jMenuBar1.add(jMenu7);

        jMenu1.setText("Hệ thống");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/delete.png"))); // NOI18N
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/open.png"))); // NOI18N
        jMenuItem4.setText("Open Database");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("    ");
        jMenuBar1.add(jMenu2);

        jMenu.setText("Chức năng");
        jMenu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jMenuItem_Balo1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_Balo1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem_Balo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/balo_16.png"))); // NOI18N
        jMenuItem_Balo1.setText("Bài toán Balo 1");
        jMenuItem_Balo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Balo1ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem_Balo1);
        jMenu.add(jSeparator2);

        jMenuItem_Balo2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_Balo2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem_Balo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/balo2_16.png"))); // NOI18N
        jMenuItem_Balo2.setText("Bài toán Balo 2");
        jMenuItem_Balo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Balo2ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem_Balo2);
        jMenu.add(jSeparator4);

        jMenuItem_Balo3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_Balo3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem_Balo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/balo3_16.png"))); // NOI18N
        jMenuItem_Balo3.setText("Bài toán Balo 3");
        jMenuItem_Balo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Balo3ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem_Balo3);

        jMenuBar1.add(jMenu);

        jMenu6.setText("   ");
        jMenuBar1.add(jMenu6);

        jMenu3.setText("Trợ giúp");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jMenuItem_HDSD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_HDSD.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem_HDSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/help.png"))); // NOI18N
        jMenuItem_HDSD.setText("Hướng dẫn sử dụng");
        jMenuItem_HDSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_HDSDActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_HDSD);
        jMenu3.add(jSeparator3);

        jMenuItem_GioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_GioiThieu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem_GioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/them.png"))); // NOI18N
        jMenuItem_GioiThieu.setText("Giới thiệu");
        jMenuItem_GioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GioiThieuActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_GioiThieu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_GioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GioiThieuActionPerformed
        AboutFormDialog ab = new AboutFormDialog(this, true);
        ab.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GioiThieuActionPerformed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        AboutFormDialog ab = new AboutFormDialog(this, true);
        ab.setVisible(true);
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_Balo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Balo1ActionPerformed
        if(balo1Form  == null || !jTabbedPane.isAncestorOf(balo1Form)){
            balo1Form = new Balo1Form();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/balo_16.png"));
            jTabbedPane.addTab("Bài toán Balo 1", icon,balo1Form,"Bài toán Balo 1");
        }
        jTabbedPane.setSelectedComponent(balo1Form);
    }//GEN-LAST:event_jButton_Balo1ActionPerformed

    private void jButton_Balo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Balo2ActionPerformed
        if(balo2Form  == null || !jTabbedPane.isAncestorOf(balo2Form)){
            balo2Form = new Balo2Form();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/balo2_16.png"));
            jTabbedPane.addTab("Bài toán Balo 2", icon,balo2Form,"Bài toán Balo 2");
        }
        jTabbedPane.setSelectedComponent(balo2Form);
    }//GEN-LAST:event_jButton_Balo2ActionPerformed

    private void jButton_Balo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Balo3ActionPerformed
        if(balo3Form  == null || !jTabbedPane.isAncestorOf(balo3Form)){
            balo3Form = new Balo3Form();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/balo3_16.png"));
            jTabbedPane.addTab("Bài toán Balo 3", icon,balo3Form,"Bài toán Balo 3");
        }
        jTabbedPane.setSelectedComponent(balo3Form);
    }//GEN-LAST:event_jButton_Balo3ActionPerformed

    private void jButton_Balo3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton_Balo3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Balo3AncestorAdded

    private void jMenuItem_Balo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Balo1ActionPerformed
        if(balo1Form  == null || !jTabbedPane.isAncestorOf(balo1Form)){
            balo1Form = new Balo1Form();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/balo_16.png"));
            jTabbedPane.addTab("Bài toán Balo 1", icon,balo1Form,"Bài toán Balo 1");
        }
        jTabbedPane.setSelectedComponent(balo1Form);
    }//GEN-LAST:event_jMenuItem_Balo1ActionPerformed

    private void jMenuItem_Balo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Balo2ActionPerformed
        if(balo2Form  == null || !jTabbedPane.isAncestorOf(balo2Form)){
            balo2Form = new Balo2Form();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/balo2_16.png"));
            jTabbedPane.addTab("Bài toán Balo 2", icon,balo2Form,"Bài toán Balo 2");
        }
        jTabbedPane.setSelectedComponent(balo2Form);
    }//GEN-LAST:event_jMenuItem_Balo2ActionPerformed

    private void jMenuItem_Balo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Balo3ActionPerformed
        if(balo3Form  == null || !jTabbedPane.isAncestorOf(balo3Form)){
            balo3Form = new Balo3Form();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/balo3_16.png"));
            jTabbedPane.addTab("Bài toán Balo 3", icon,balo3Form,"Bài toán Balo 3");
        }
        jTabbedPane.setSelectedComponent(balo3Form);
    }//GEN-LAST:event_jMenuItem_Balo3ActionPerformed

    private void jButton_Balo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Balo1MouseEntered
        jButton_Balo1.setToolTipText("Balo 1 được chọn các sản phẩm có số lượng không giới hạn");
    }//GEN-LAST:event_jButton_Balo1MouseEntered

    private void jButton_Balo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Balo1MouseExited
        jButton_Balo1.setToolTipText(" ");
    }//GEN-LAST:event_jButton_Balo1MouseExited

    private void jButton_Balo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Balo2MouseEntered
        jButton_Balo2.setToolTipText("Balo 2 được chọn các sản phẩm có số lượng giới hạn");
    }//GEN-LAST:event_jButton_Balo2MouseEntered

    private void jButton_Balo2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Balo2MouseExited
        jButton_Balo2.setToolTipText(" ");
    }//GEN-LAST:event_jButton_Balo2MouseExited

    private void jButton_Balo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Balo3MouseEntered
        jButton_Balo3.setToolTipText("Balo 3 được chọn các sản phẩm có số lượng là 1");
    }//GEN-LAST:event_jButton_Balo3MouseEntered

    private void jButton_Balo3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Balo3MouseExited
        jButton_Balo3.setToolTipText(" ");
    }//GEN-LAST:event_jButton_Balo3MouseExited

    private void jButton_HuongDanSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HuongDanSDActionPerformed
        if(instructionsForUsePanel  == null || !jTabbedPane.isAncestorOf(instructionsForUsePanel)){
            instructionsForUsePanel = new InstructionsForUsePanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/huongdansd_16.png"));
            jTabbedPane.addTab("Hướng dẫn sử dụng", icon,instructionsForUsePanel,"Hướng dẫn sử dụng");
        }
        jTabbedPane.setSelectedComponent(instructionsForUsePanel);
    }//GEN-LAST:event_jButton_HuongDanSDActionPerformed

    private void jMenuItem_HDSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_HDSDActionPerformed
        // TODO add your handling code here:
        if(instructionsForUsePanel  == null){
            instructionsForUsePanel = new InstructionsForUsePanel();
            ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/icon/balo2_16.png"));
            jTabbedPane.addTab("Hướng dẫn sử dụng", icon,instructionsForUsePanel,"Hướng dẫn sử dụng");
        }
        jTabbedPane.setSelectedComponent(instructionsForUsePanel);
    }//GEN-LAST:event_jMenuItem_HDSDActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jTabbedPane.getSelectedIndex();
        if (selectedIndex != -1) {
            jTabbedPane.removeTabAt(selectedIndex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToolBar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolBar1MouseEntered
//        jToolBar1.setVisible(true);
        
    }//GEN-LAST:event_jToolBar1MouseEntered

    private void jToolBar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToolBar1MouseExited
//        jToolBar1.setVisible(false);
    }//GEN-LAST:event_jToolBar1MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_jButton1MouseExited

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            // Thay đổi đường dẫn dưới đây nếu MySQL Workbench của bạn được cài ở một đường dẫn khác.
            String mysqlWorkbenchPath = "C:\\Program Files\\MySQL\\MySQL Workbench 8.0\\MySQLWorkbench.exe";
            
            // Mở MySQL Workbench sử dụng lớp Runtime
            Runtime.getRuntime().exec(mysqlWorkbenchPath);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Balo1;
    private javax.swing.JButton jButton_Balo2;
    private javax.swing.JButton jButton_Balo3;
    private javax.swing.JButton jButton_HuongDanSD;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem_Balo1;
    private javax.swing.JMenuItem jMenuItem_Balo2;
    private javax.swing.JMenuItem jMenuItem_Balo3;
    private javax.swing.JMenuItem jMenuItem_GioiThieu;
    private javax.swing.JMenuItem jMenuItem_HDSD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
